/* eslint-disable @typescript-eslint/no-unused-vars */
import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    backgroundColor: 'white',
    height: hp('100%'),
  },
  editView: {flexDirection: 'row'},
  backButton: {marginTop: hp(3), marginLeft: wp(4), color: '#7551FD'},
  editText: {
    fontSize: hp(2.4),
    color: 'black',
    marginLeft: wp('3%'),
    fontWeight: 'bold',
    marginTop: hp(2.4),
  },
  profileImageView: {alignItems: 'center', marginTop: hp('2%')},
  profileImage: {width: wp('30%'), height: hp('14%')},
  cameraImageView: {
    width: wp(6.4),
    height: hp(3.2),
    marginTop: hp(-3.6),
    backgroundColor: 'white',
    marginLeft: wp(19),
    borderRadius: hp(4),
    borderColor: '#7551FD',
    borderWidth: 1,
  },
  cameraImage: {
    backgroundColor: 'white',
    marginLeft: wp(0.8),
    marginTop: hp(0.4),
  },
  formView: {marginTop: hp('2%')},
  firstNameView: {
    flexDirection: 'row',
    marginTop: hp(1),
    alignItems: 'center',
    height: hp('6%'),
    backgroundColor: '#F5F5F5',
    borderRadius: hp(1),
    width: wp(92),
    marginLeft: wp('4%'),
  },
  firstNameIcon: {marginLeft: wp('2%')},
  verifiedButton: {width: '4%', height: '32%', marginLeft: wp(9)},
  lastNameView: {
    flexDirection: 'row',
    marginTop: hp(1),
    alignItems: 'center',
    height: hp('6%'),
    backgroundColor: '#F5F5F5',
    borderRadius: hp(1),
    width: wp(92),
    marginLeft: wp('4%'),
  },
  lastNameIcon: {marginLeft: wp('2%')},
  input: {fontSize: hp(1.3), paddingLeft: wp(3), color: 'black', width: wp(70)},
  dropDownView: {
    width: '92%',
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: '#F5F5F5',
    alignSelf: 'center',
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 15,
  },
  dropDownText: {marginLeft: wp('2%'), fontSize: hp(1.4)},
  dropDropIcon: {
    marginLeft: wp('42%'),
  },
  pronounsDropDownList: {
    width: '92%',
    height: 70,
    borderRadius: 10,
    marginTop: 1,
    backgroundColor: '#fff',
    elevation: 5,
    alignSelf: 'center',
  },
  listView: {
    width: '85%',
    height: 26,
    marginLeft: wp(4),
    flexDirection: 'row',
    marginTop: hp(0.8),
  },
  checkBoxView: {
    borderWidth: 0.5,
    width: 16,
    height: 17,
    marginTop: hp(0.4),
    borderRadius: hp(0.4),
  },
  listText: {marginLeft: wp(2)},
  addBioView: {
    flexDirection: 'row',
    marginTop: hp(1),
    alignItems: 'center',
    height: hp('10%'),
    backgroundColor: '#F5F5F5',
    borderRadius: hp(1),
    width: wp(92),
    marginLeft: wp('4%'),
  },
  addBioIcon: {marginLeft: wp('2%'), marginBottom: hp(4)},
  editInput: {fontSize: hp(1.3), paddingLeft: wp(3), marginBottom: hp(4)},
  editBioInput: {
    fontSize: hp(1.3),
    paddingLeft: wp(2),
    marginBottom: hp(4),
    width: wp(80),
    height: hp(8),
  },
  dropDropExperIcon: {
    marginLeft: wp('52%'),
  },
  universityDropDownList: {
    width: '92%',
    height: 134,
    borderRadius: 10,
    marginTop: 1,
    backgroundColor: '#fff',
    elevation: 5,
    alignSelf: 'center',
  },
  ExpDropDownList: {
    width: '92%',
    height: 134,
    borderRadius: 10,
    marginTop: 1,
    backgroundColor: '#fff',
    elevation: 5,
    alignSelf: 'center',
  },
  buttonView: {
    alignItems: 'center',
    backgroundColor: '#7551FD',
    padding: hp(1),
    borderRadius: wp(2),
    height: hp(6),
    width: wp(92),
    marginLeft: wp(4),
    marginTop: hp(2),
  },
  buttonText: {
    fontSize: hp(1.8),
    fontWeight: 'bold',
    color: 'white',
    marginTop: hp(0.8),
  },
  loader: {marginLeft: wp(6.8)},
});
