import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  profileImageView: {
    alignItems: 'center',
    marginTop: hp(15),
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: wp(10),
    borderTopRightRadius: wp(10),
    flex: 1,
  },
  editView: {
    width: wp(6),
    height: hp(3),
    backgroundColor: 'white',
    marginTop: hp(-2),
    borderRadius: hp(2),
    borderWidth: 1,
    borderColor: '#A689E1',
  },
  editImage: {marginLeft: wp(1), marginTop: hp(0.4)},
  editText: {
    width: wp(20),
    alignSelf: 'center',
    marginTop: hp(1),
    fontSize: hp(1),
    marginLeft: wp(8),
    fontFamily: '400',
  },
  Line1: {
    height: hp(8),
    width: 1,
    backgroundColor: '#CCBEFF',
    margin: hp(2),
    marginLeft: wp(20),
    marginTop: hp(3),
  },
  universityListView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginLeft: wp(4),
    marginTop: hp(1),
    width: wp(100),
  },
  selectedListView: {
    backgroundColor: 'rgba(117, 81, 253, 0.1)',
    width: wp(43),
    height: hp(5),
    borderRadius: hp(1),
    marginTop: hp(0.5),
    marginLeft: wp(1.4),
    margin: wp(2),
  },
  selectedListViewText: {
    fontSize: hp(1.5),
    alignSelf: 'center',
    marginTop: hp(1.2),
    color: '#000000',
  },
  line: {
    width: wp('100%'),
    borderWidth: 1,
    borderColor: '#D2D2D2',
    marginTop: hp(3),
  },
  universityView: {marginTop: hp(3), flexDirection: 'row', alignSelf: 'center'},
  deleteView: {
    marginTop: hp(3),
    flexDirection: 'row',
    alignSelf: 'center',
    marginBottom: hp(4),
  },
  universityText: {
    fontSize: hp(2),
    alignSelf: 'center',
    color: '#7551FD',
    fontWeight: '600',
  },
  capImage: {marginTop: hp(0.5), marginRight: wp(3)},
  deleteText: {
    fontSize: hp(2),
    alignSelf: 'center',
    color: '#858585',
    fontWeight: '600',
  },
  bottomTabView: {
    elevation: 35,
    paddingVertical: 15,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowOpacity: 18,
    shadowRadius: 10,
    shadowOffset: {
      height: 10,
      width: 1,
    },
  },
  homeIcon: {marginRight: wp(14)},
  universityIcon: {marginRight: wp(16)},
  container: {backgroundColor: '#7551fd1a', flex: 1},
  profileImage: {marginTop: hp(-10)},
  profileName: {fontSize: hp(2.8), color: '#000000', fontWeight: '600'},
  profileNameView: {marginTop: hp(4)},
  locationView: {flexDirection: 'row', marginTop: hp(1)},
  locationIcon: {marginTop: hp(0.4)},
  locationText: {color: '#858585'},
  bioTextOne: {marginTop: hp(2), color: '#1B1A1A'},
  bioTextTwo: {color: '#1B1A1A'},
  experienceView: {flexDirection: 'row', marginTop: hp(2)},
  universityTextView: {alignSelf: 'center', marginRight: wp(-6)},
  univerText: {
    marginTop: hp(-0.3),
    fontSize: hp(1.8),
    fontWeight: '600',
    color: '#858585',
  },
  capIcon: {alignSelf: 'center'},
  expTextView: {alignSelf: 'center', marginLeft: wp(6)},
  expText: {
    marginTop: hp(-0.3),
    fontSize: hp(1.8),
    fontWeight: '600',
    color: '#858585',
  },
});
