/* eslint-disable @typescript-eslint/no-unused-vars */
import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    backgroundColor: 'white',
    height: hp('100%'),
  },
  profileView: {flexDirection: 'row'},
  backButton: {marginTop: hp(3), marginLeft: wp(4), color: '#7551FD'},
  profileText: {
    fontSize: hp(2.4),
    color: 'black',
    marginLeft: wp(6),
    fontWeight: '600',
    marginTop: hp(2.4),
  },
  profileImageView: {alignItems: 'center', marginTop: hp(2.4)},
  profileImage: {
    marginLeft: wp(0.8),
    marginTop: hp(-12),
  },
  editView: {
    width: wp(6),
    height: hp(3),
    backgroundColor: 'white',
    marginTop: hp(-2),
    borderRadius: hp(2),
    borderWidth: 1,
    borderColor: '#A689E1',
  },
  editImage: {marginLeft: wp(1), marginTop: hp(0.4)},
  editText: {
    width: wp(20),
    alignSelf: 'center',
    marginTop: hp(1),
    fontSize: hp(1),
    marginLeft: wp(8),
    fontFamily: '400',
  },
  profileNameView: {marginTop: hp(4)},
  studentNameView: {marginTop: hp(1.4)},
  profileNameText: {
    fontSize: hp(3),
    alignSelf: 'center',
    color: '#000000',
    fontWeight: '500',
  },
  studentText: {
    fontSize: hp(1.6),
    alignSelf: 'center',
    color: '#858585',
    fontWeight: '400',
  },
  bioTextView: {marginTop: hp(1.4), alignSelf: 'center'},
  bioTextOne: {
    fontSize: hp(1.4),
    marginLeft: wp(2),
    color: '#1B1A1A',
    fontWeight: '400',
  },
  bioTextTwo: {
    fontSize: hp(1.4),
    marginLeft: wp(2),
    color: '#1B1A1A',
    fontWeight: '400',
    alignSelf: 'center',
  },
  line: {
    width: wp('100%'),
    borderWidth: 1,
    borderColor: '#D2D2D2',
    marginTop: hp(3),
  },
  universityView: {marginTop: hp(3), flexDirection: 'row', alignSelf: 'center'},
  universityText: {
    fontSize: hp(2),
    alignSelf: 'center',
    color: '#7551FD',
    fontWeight: '600',
  },
  capImage: {marginTop: hp(0.5), marginRight: wp(3)},
  universityListView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginLeft: wp(5),
    marginTop: hp(2),
    width: wp(280),
  },
  selectedListView: {
    backgroundColor: 'rgba(117, 81, 253, 0.1)',
    width: wp(43),
    height: hp(5),
    borderRadius: hp(1),
    marginTop: hp(0.5),
    marginLeft: wp(1.4),
    margin: wp(2),
  },
  selectedListViewText: {
    fontSize: hp(1.5),
    alignSelf: 'center',
    marginTop: hp(1.2),
    color: '#000000',
  },
  lineTwo: {
    width: wp('100%'),
    borderWidth: 1,
    borderColor: '#D2D2D2',
    marginTop: hp(2),
  },
  deleteText: {
    fontSize: hp(2),
    alignSelf: 'center',
    color: '#858585',
    fontWeight: '600',
  },
  bottomTabView: {
    elevation: 35,
    paddingVertical: 15,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowOpacity: 18,
    shadowRadius: 10,
    shadowOffset: {
      height: 10,
      width: 1,
    },
  },
  homeIcon: {marginRight: wp(14)},
  universityIcon: {marginRight: wp(16)},
  topicListView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginLeft: wp(5),
    marginTop: hp(2),
    width: wp(210),
  },
  topicSelectedListView: {
    backgroundColor: 'rgba(117, 81, 253, 0.1)',
    width: wp(43),
    height: hp(5),
    borderRadius: hp(1),
    marginTop: hp(0.5),
    marginLeft: wp(1.4),
    margin: wp(2),
  },
  topicSelectedListText: {
    fontSize: hp(1.5),
    alignSelf: 'center',
    marginTop: hp(1.2),
    color: '#000000',
  },
});
