/* eslint-disable @typescript-eslint/no-unused-vars */
import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    backgroundColor: 'white',
    height: hp('100%'),
  },
  profiletext: {
    fontSize: hp(2.4),
    color: 'black',
    marginLeft: wp('6%'),
    fontWeight: 'bold',
    marginTop: hp(2),
  },
  profileimagesview: {alignItems: 'center', marginTop: hp('2%')},
  profileimage: {width: wp('30%'), height: hp('14%')},
  cameraimageview: {
    marginLeft: hp('6%'),
    marginTop: hp('-3%'),
  },
  cameraimage: {width: wp('5%'), height: hp('3%'), borderRadius: hp('5%')},
  firstnameview: {
    flexDirection: 'row',
    marginTop: hp(1),
    alignItems: 'center',
    height: hp('6%'),
    backgroundColor: '#F5F5F5',
    borderRadius: hp(1),
    width: wp(92),
    marginLeft: wp('4%'),
  },
  firstnameprofile: {marginLeft: wp('2%')},
  input: {fontSize: hp(1.3), paddingLeft: wp(3)},
  dropdownlistview: {
    width: wp(92),
    marginTop: hp(1),
    marginLeft: wp('4%'),
  },
  buttonview: {
    alignItems: 'center',
    backgroundColor: '#A689E1',
    padding: hp(1),
    borderRadius: wp(2),
    height: hp(6),
    width: wp(92),
    marginLeft: wp(4),
    marginTop: hp(1),
  },
  buttontext: {
    fontSize: hp(1.8),
    fontWeight: 'bold',
    color: 'white',
    paddingTop: hp(1),
  },
  cameraicon: {backgroundColor: 'white', borderRadius: wp(2)},
  formview: {marginTop: hp('5%')},
  dropdownview: {
    width: '92%',
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: '#F5F5F5',
    //borderColor: 'red',
    alignSelf: 'center',
    marginTop: 10,
    //marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 15,
  },
  dropdowntext: {marginLeft: wp('2%'), fontSize: hp(1.4)},
  dropicon: {
    marginLeft: wp('42%'),
  },
  dropdownlist: {
    width: '92%',
    height: 162,
    borderRadius: 10,
    marginTop: 1,
    backgroundColor: '#fff',
    elevation: 5,
    alignSelf: 'center',
  },
  listview: {
    width: '85%',
    height: 26,
    marginLeft: wp(4),
    flexDirection: 'row',
    marginTop: hp(0.8),
  },
  label: {
    textAlign: 'center',
    marginBottom: 10,
    fontSize: 24,
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    //marginBottom: hp(1),
  },
  button: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: 'oldlace',
    alignSelf: 'flex-start',
    marginHorizontal: '1%',
    marginBottom: 6,
    minWidth: '48%',
    textAlign: 'center',
  },
  selected: {
    backgroundColor: 'coral',
    borderWidth: 0,
  },
  buttonLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: 'coral',
  },
  selectedLabel: {
    color: 'white',
  },
  checkboxview: {
    borderWidth: 0.5,
    width: 16,
    height: 17,
    marginTop: hp(0.4),
    borderRadius: hp(0.4),
  },
  universitydropdownlist: {
    width: '92%',
    height: 180,
    borderRadius: 10,
    marginTop: 1,
    backgroundColor: '#fff',
    elevation: 5,
    alignSelf: 'center',
  },
  selectedlistview: {
    borderWidth: 1,
    borderColor: '#A689E1',
    width: wp(43),
    height: hp(5),
    borderRadius: hp(5),
    marginTop: hp(1),
    marginLeft: wp(1.4),
  },
  selectedlistviewtext: {
    fontSize: 11,
    alignSelf: 'center',
    marginTop: hp(1.3),
  },
  checkicon: {marginTop: hp(0.1), marginLeft: wp(0.1)},
});
